# Generated by Django 3.1.3 on 2020-11-28 12:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post2',
            new_name='BlogPractice',
        ),
    ]
