# Generated by Django 3.1.3 on 2020-11-28 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('practice01', '0003_auto_20201129_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpractice',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
